initial_x: 1.39
initial_y: 1.2
initial_z: 0.5
initial_roll: 0
initial_pitch: 0
initial_yaw: 0
from: base
to: table
save_to_package: ros_finger_sensor
file_name: /config/tf_to_table.yaml
topic_name: /keyboard_base_to_table/keydown
